### ISSUE TITLE
NullInjectorError: No provider for InjectionToken @gewd/lazy-loader/LazyModuleComponentConfig !

### ISSUE THREAD

**Issue by zamadaouf** [negue/gewd#119]
I recently created a new Angular project using Angular CLI version 16. Afterward, I installed @gewd/lazy version 1.0.0, and imported GewdLazyLoaderModule into my AppModule then ran the ng serve command. However, I encountered an issue where the project compiled successfully but did not run.

I have made several attempts to resolve this issue, but unfortunately, none of them have yielded positive results.

I consistently receive the following error message :
![gewd_nullInjector](https://github.com/negue/gewd/assets/50621295/e890dce7-b667-4bc6-bd84-4fe9052c2c19)

I would greatly appreciate it if you could provide guidance or assistance in resolving this issue. Any insights or recommendations you can offer would be incredibly helpful.

Thank you in advance for your support.

**Comment by negue** [comment]
I think my Description in https://github.com/negue/gewd/blob/master/libs/lazy/README.md#lazy-module-components  is a bit off, you always need the `.withLazy(` Module import, since that injects the needed Config see the example linked or this of the example app https://github.com/negue/gewd/blob/1f7ac8d0fe9d03cb00f467cd139f5c084bcee5de/apps/demo/src/app/examples/lazyload-example/lazyload-example.module.ts#L22


I'll update the Readme to remove the following

```
GewdLazyLoaderModule 

// or with .withLazy
```

try it again with `.withLazy` as Module

**Comment by zamadaouf** [comment]
> I think my Description in https://github.com/negue/gewd/blob/master/libs/lazy/README.md#lazy-module-components is a bit off, you always need the `.withLazy(` Module import, since that injects the needed Config see the example linked or this of the example app
> 
> https://github.com/negue/gewd/blob/1f7ac8d0fe9d03cb00f467cd139f5c084bcee5de/apps/demo/src/app/examples/lazyload-example/lazyload-example.module.ts#L22
> 
> I'll update the Readme to remove the following
> 
> ```
> GewdLazyLoaderModule 
> 
> // or with .withLazy
> ```
> 
> try it again with `.withLazy` as Module

Working: ✅

I greatly appreciate your time and effort in helping me navigate this issue.

**Comment by negue** [comment]
Awesome - I'm glad it was exactly that 🎉
